# Generated by Django 5.0.7 on 2024-08-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_account_id_alter_account_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
