# Generated by Django 5.0.7 on 2024-08-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.IntegerField(db_index=True, default=2000, unique=True),
        ),
    ]
