# Generated by Django 5.0.7 on 2024-08-09 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_account_account_id'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='person.person'),
        ),
    ]
