# Generated by Django 5.0.7 on 2024-08-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_account_amount_alter_account_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
