# Generated by Django 5.0.7 on 2024-08-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_account_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
